name: CI
on:
  push:
    branches: [main]
  pull_request:

env:
  NEXT_PUBLIC_SUPABASE_URL:  ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
  NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
  SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
  SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_SUPABASE_URL:  ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20', cache: 'npm', cache-dependency-path: package-lock.json }
      - name: Install deps
        run: npm ci --prefer-offline
      - run: npm ci
      - run: npm run lint && npm run build

  migrate-db:
    needs: build-test
    runs-on: ubuntu-latest
    environment: production
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with: { version: latest }
      - name: Link Supabase project
        run: supabase link --project-ref $SUPABASE_PROJECT_REF
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_REF:  ${{ secrets.SUPABASE_PROJECT_REF }}
      - name: Push migrations to Production DB
        env:
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          SUPABASE_PROJECT_REF:  ${{ secrets.SUPABASE_PROJECT_REF }}
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          supabase db push

  preview-db:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with: { version: latest }

      - name: Create Branch DB & push migrations
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_REF:  ${{ secrets.SUPABASE_PROJECT_REF }}
          SUPABASE_PLAN:         ${{ secrets.SUPABASE_PLAN }}
        run: |
          set -e
          PLAN="${SUPABASE_PLAN:-$(supabase --experimental projects get $SUPABASE_PROJECT_REF -o json | jq -r '.plan')}"
          echo "Plan=$PLAN"
          if [ "$PLAN" = "Free" ] || [ "$PLAN" = "free" ]; then
            echo "Skip preview DB on Free plan"
            exit 0
          fi
          SAFE_REF="${{ github.head_ref }}" && SAFE_REF="${SAFE_REF//\//-}"

          supabase --experimental branches create "$SAFE_REF" \
            --project-ref "$SUPABASE_PROJECT_REF" \
            --region ap-northeast-1 \
            --size micro

          supabase --experimental branches get "$SAFE_REF" -o env >> $GITHUB_ENV

          supabase db push --db-url "$POSTGRES_URL_NON_POOLING"