name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        continue-on-error: true

      - name: Run Lint
        run: npm run lint
        continue-on-error: true

      - name: Run Tests
        run: npm run test --if-present
        continue-on-error: true

      - name: Build
        run: npm run build
        continue-on-error: true

      - name: Upload Logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: ${{ runner.temp }}/_github_workflow/**

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          model: "claude-sonnet-4-20250514"
          allowed_tools: "Bash,Read,Edit,Write,MultiEdit,Glob,Grep,LS"
          custom_instructions: |
            Follow the instructions in CLAUDE.md file for project-specific guidance.
            Run npm run lint and npm run typecheck before committing any changes.
